name: Swift Package Analysis

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * *'  # Scheduled run every day at midnight

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas requests

      - name: Run Swift Package Analysis Script
        run: |
          python swift_package_analysis.py  # Run your Python script

      - name: Commit Results if Changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add results/
          git diff --exit-code || git commit -m "Update Swift Package Analysis Results"
          git push